# Generated by Django 3.2.3 on 2021-06-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
    ]
