# Generated by Django 3.2.3 on 2021-06-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_blogcomment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
