# Generated by Django 3.2.3 on 2021-06-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
