# Generated by Django 3.2.3 on 2021-06-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
