# Generated by Django 3.2.3 on 2021-06-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
