# Generated by Django 3.2.3 on 2021-06-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
