# Generated by Django 3.2.3 on 2021-06-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_commentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
